name: Nar24
description: Kuzey Kıbrıs'ın En Gelişmiş E-Ticaret Platformu.
publish_to: none
version: 1.0.4+57

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  get: ^4.6.1
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.0
  flutter_image_compress: ^2.4.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  google_sign_in: ^7.2.0
  share_plus: ^10.1.4
  go_router: ^17.0.0
  firebase_app_check: ^0.4.1+1
  url_launcher: ^6.3.2
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  badges: ^3.1.2
  google_fonts: ^6.3.0
  http: ^1.2.2
  timeago: ^3.6.0
  file_picker: ^10.3.7
  uuid: ^4.5.1
  async: ^2.11.0
  flutter_svg: ^2.0.16
  flutter_localization: ^0.3.0
  intl: 0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  flutter_colorpicker: ^1.1.0
  video_player: ^2.9.3
  fluttertoast: ^8.2.12
  cloud_functions: ^6.0.3
  algoliasearch: ^1.28.3
  marquee: ^2.3.0
  syncfusion_flutter_charts: ^31.2.16
  flutter_rating_bar: ^4.0.1
  collection: ^1.19.0
  flutter_spinkit: ^5.2.1
  permission_handler: ^12.0.1
  rxdart: ^0.28.0
  fl_chart: ^0.70.0
  flutter_typeahead: ^5.2.0
  flutter_feather_icons: ^2.0.0+1
  flutter_secure_storage: ^9.2.3
  dotted_border: ^2.1.0
  styled_widget: ^0.4.1
  font_awesome_flutter: ^10.8.0
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.5
  tuple: ^2.0.2
  retry: ^3.1.2
  connectivity_plus: ^7.0.0
  palette_generator: ^0.3.3+7
  shimmer: ^3.0.0
  popup_menu: ^2.1.0
  app_links: ^6.4.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  geolocator: ^14.0.2
  pdf: ^3.11.3
  printing: ^5.14.2
  device_info_plus: ^12.1.0
  webview_flutter: ^4.13.0
  flutter_polyline_points: ^3.1.0
  firebase_crashlytics: ^5.0.3
  firebase_performance: ^0.11.1+1
  firebase_analytics: ^12.0.4
  firebase_remote_config: ^6.1.3
  package_info_plus: ^8.0.0
  sentry_flutter: ^9.9.0
  sign_in_with_apple: ^7.0.1

  flutter_localizations:
    sdk: flutter
  sqflite: any
  path: any
  crypto: any
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
flutter_icons:
  android: 'ic_launcher'
  ios: true
  image_path: 'assets/images/naricon.png'
  remove_alpha_ios: true
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/naricon.png'

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/agreements/
    - lib/constants/categories.json
    - assets/images/narsplash.mp4
    - assets/images/naricon.png
    - assets/images/nargri.png
    - assets/images/logo.png
    - assets/images/coupon.png
    - assets/images/tick.png
    - assets/images/beyazlogo.png
    - assets/images/siyahlogo.png
    - assets/images/support.png
    - assets/images/empty-search-result.png
    - assets/images/asktoseller.png
    - assets/images/empty-address.png
    - assets/images/empty-cart.png
    - assets/images/empty-product2.png
    - assets/images/empty-box.png
    - assets/images/digital-inventory.png
    - assets/images/payment1.png
    - assets/images/success.gif
    - assets/images/fastdelivery.png
    - assets/images/selfdelivery.png
    - assets/images/credit-card-payment.png
    - assets/images/empty-product.png
    - assets/images/narsiyah.png
    - assets/images/vitrinbubble.png
    - assets/images/foodbubble.png
    - assets/images/marketbubble.png
    - assets/images/shopbubble.png
    - assets/images/questions.png
    - assets/images/reviews.png
    - assets/images/mobile-notification.png
    - assets/images/google_icon.png
    - assets/images/verified4.png
    - assets/images/verify2.png
    - assets/images/verify3.gif
    - assets/images/default_avatar.png
    - assets/images/visa.png
    - assets/images/mastercard.png
    - assets/images/playpoint.png
    - assets/images/caution.png
    - assets/images/gmail.png
    - assets/images/category-boxes/fashion.jpg
    - assets/images/category-boxes/accessories.jpg
    - assets/images/category-boxes/child.jpg
    - assets/images/category-boxes/furniture.jpg
    - assets/images/category-boxes/flowerandgift.jpg
    - assets/images/category-boxes/sport.jpg
    - assets/images/category-boxes/electronics.jpg
    - assets/images/category-boxes/bags.jpg
    - assets/images/category-boxes/healthandwellness.jpg
    - assets/images/category-boxes/automotive.jpg
    - assets/images/category-boxes/stationary.jpg
    - assets/images/category-boxes/toolsandhardware.jpg
    - assets/images/category-boxes/pets.jpg
    - assets/images/category-boxes/shoes.jpg
    - assets/images/category-boxes/selfcare.jpg

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-VariableFont_wght.ttf
